import { StyleSheet } from "react-native";

const darkstyles = StyleSheet.create({
  body: {
    fontFamily: "Arial, sans-serif",
    backgroundColor: "#121212",
    height: "100%",
    margin: 0,
    color: "#fff",
  },
  container: {
    textAlign: "center",
  },
  title: {
    textAlign: "center",
    fontSize: 40,
    fontWeight: "bold",
    color: "#e0e0e0",
  },
  subtitle: {
    textAlign: "center",
    fontSize: 16,
    color: "#b0b0b0",
    marginBottom: 20,
  },
  converter: {
    backgroundColor: "#1f1f1f",
    padding: 30,
    borderRadius: 10,
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.3)",
    display: "inline-block",
    textAlign: "left",
  },
  label: {
    fontSize: 14,
    color: "#e0e0e0",
    marginBottom: 10,
  },
  converterAmount: {
    width: "100%",
    padding: 10,
    fontSize: 24,
    marginBottom: 20,
    border: "1px solid #444",
    backgroundColor: "#333",
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 12,
    color: "#fff",
    textAlign: "left",
  },

  converterSelect: {
    marginTop: 10,
    //width: "calc(50% - 10px)",
    padding: 10,
    fontSize: 16,
    marginBottom: 20,
    border: "1px solid #444",
    borderRadius: 5,
    backgroundColor: "#333",
    borderWidth: 1,
    borderColor: "#555",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 12,
    color: "#fff",
  },
  Swap: {
    display: "inline-block",
    width: 20,
    textAlign: "center",
    fontSize: 24,
    color: "#b0b0b0",
    marginBottom: 15,
    marginLeft: "50%",
    marginRight: "50%",
  },
  convertedAmount: {
    display: "block",
    fontSize: 24,
    fontWeight: "bold",
    color: "#e0e0e0",
    marginBottom: 5,
    textAlign: "center",
  },
  exchangeRate: {
    fontSize: 14,
    color: "#b0b0b0",
    textAlign: "center",
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    backgroundColor: "#333",
  },
  icon: {
    width: 24,
    height: 24,
    marginRight: 13,
    marginLeft: 25,
  },
  itemText: {
    fontSize: 16,
    marginRight: 15,
    color: "#fff",
  },
  iconContainer: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: "50%",
    padding: 10,
  },
});

export default darkstyles;
